name: Jira Add Comment
description: Add a comment to an issue
branding:
  icon: 'align-left'
  color: 'blue'
inputs:
  issue:
    description: Key of the issue to be commented on
    required: true
  comment:
    description: Comment
    required: true
  role_name:
    description: JIRA Role Name
    required: false
  role_id:
    description: JIRA Role ID
    required: false
runs:
  using: 'node12'
  main: './dist/index.js'
